handle_map = {
    "@amelielens": "amelie lens",
    "@anfisaletyago": "anfisa letyago",
    "@annalunoe": "anna lunoe",
    "@antiupmusic": "anti up",
    "@artbatmusic": "artbar",
    "@avision": "avision",
    "@biscitsmusic": "biscits",
    "@blackvneckmusic": "black v neck",
    "@blucu": "egregious philbin",
    "@camelphat": "camelphat",
    "@carlolio": "carlo lio",
    "@charlottedwitte": "charlotte de witte",
    "@claptone_": "claptone",
    "@clarity_sounds": "clarity",
    "@deeperpurpose92": "deeper purpose",
    "@djjohndigweed": "john digweed",
    "@djmarkfarina": "mark farina",
    "@djmarkknight": "mark knight",
    "@domdolla": "dom dolla",
    "@dosem": "dosem",
    "@dubfire": "dubfire",
    "@elibrownbeats": "eli brown",
    "@ellenallien": "ellen allien",
    "@ericprydz": "eric prydz",
    "@fredagainagain1": "fred again",
    "@honeyluvmusic": "honeyluv",
    "@hotsince82": "hot since 82",
    "@idaengberg": "ida engberg",
    "@jamiejonesmusic": "jamie jones",
    "@johnsummit": "john summit",
    "@justinmartin": "justin martin",
    "@kaskade": "kaskade",
    "@klangkuenstler": "klangkuenstler",
    "@kx5official": "kx5",
    "@lane8music": "lane 8",
    "@leyouth": "le youth",
    "@lillypalmerdj": "lilly palmer",
    "@locodiceofc": "loco dice",
    "@lorenzosbeats": "chris lorenzo",
    "@lucatimusic": "lucati",
    "@maceoplex": "maceoplex",
    "@marckinchen": "marc kinchen",
    "@matrodamusic": "matroda",
    "@mattsassari": "matt sassari",
    "@michaelbibi1": "michael bibi",
    "@mochakkmusic": "mochakk",
    "@nastia_dj": "nastia",
    "@nicolemoudaber": "nicole moudaber",
    "@ninakraviz": "nina kraviz",
    "@official_hilo": "hi-lo",
    "@osexbeats": "os beats",
    "@paco_osuna": "paco osuna",
    "@pawsaofficial": "pawsa",
    "@purplediscom": "purple disco machine",
    "@rebukemusic": "rebuke",
    "@saralandrydj": "sara landry",
    "@sashaofficial": "sasha",
    "@solidgrooves_": "solid grooves",
    "@sonnyfodera": "sonny fodera",
    "@taleofus": "tale of us",
    "@thisisnalaa": "nalaa",
    "@tinlicker_nl": "tinlicker",
    "@toliptset": "testpilot",
    "@trymlegit": "trym",
    "@vnssamusic": "vnssa",
    "@walkerandroyce": "walker and royce",
    "@yottomusic": "yotto",
    "@zhumusic": "zhu",

    # some stuff I noticed
    "ihatemodels": "i hate models"
}